### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by yakhyadabo** [geerlingguy/ansible-role-docker#29] opened 2017-09-25 08:14 UTC
Deleted

**Comment by josalmi** [comment] 2017-09-25 12:12
Did you find a solution for this issue?

I'm having the same issue with minimal setup using Vagrant.

```ruby
# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

```yml
---
- hosts: all
  roles:
    - geerlingguy.docker
```

Here is the output of `vagrant up`:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Checking if box 'centos/7' is up to date...
...
==> default: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.4.0.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    default: Running ansible-playbook...
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [geerlingguy.docker : Ensure old versions of Docker are not installed.] ***
ok: [default] => (item=docker)
ok: [default] => (item=docker-common)
ok: [default] => (item=docker-engine)

TASK [geerlingguy.docker : Add Docker GPG key.] ********************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "gpg: no valid OpenPGP data found.\ngpg: processing message failed: Unknown system error\n"}
	to retry, use: --limit @/Users/josalmi/Projects/.../playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=2    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by yakhyadabo** [comment] 2017-09-25 12:27
Can you try to add **centos-epel-repo** before installing docker ? 

roles:
    - geerlingguy.centos-epel-repo
    - geerlingguy.docker

**Comment by josalmi** [comment] 2017-09-25 12:34
I couldn't find `geerlingguy.centos-epel-repo` role, but I used `geerlingguy.repo-epel` which caused similar issues:
```
TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [geerlingguy.repo-epel : Check if EPEL repo is already configured.] *******
ok: [default]

TASK [geerlingguy.repo-epel : Install EPEL repo.] ******************************
changed: [default]

TASK [geerlingguy.repo-epel : Import EPEL GPG key.] ****************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "gpg: no valid OpenPGP data found.\ngpg: processing message failed: Unknown system error\n"}
```

**Comment by yakhyadabo** [comment] 2017-09-25 12:37
Yes, **geerlingguy.repo-epel** is the right role.  
I have similar behavior. It fails at the first attempt and works at the second one.

**Comment by mbaig25** [comment] 2017-10-02 15:54
@yakhyadabo @josalmi I'm having the same problem with **repo-epel** and **repo-remi**. Have you guys found a solution to the problem? I'm using Ansible version 2.4.0 on macOS. Using Vagrant with the latest Centos 7 image. At the time of writing this: centos/7 v1708.1

**Comment by geerlingguy** [comment] 2017-10-04 14:55
Can you reproduce this using the vagrant box `geerlingguy/centos7`? I know I've run into weird issues using the official vagrant box in the past.

**Comment by geerlingguy** [comment] 2017-10-04 14:55
This role runs all it's tests on a cron job, daily (https://travis-ci.org/geerlingguy/ansible-role-docker), and hasn't seen any failures using the Docker CentOS 7 image either.

**Comment by mbaig25** [comment] 2017-10-04 21:16
Both **repo-epel** and **repo-remi** seem to import gpg key fine on `geerlingguy/centos7` using Ansible 2.4.

@geerlingguy I'm wondering if it errors out on a vanilla CentOS box would also error on a Vanilla RHEL VM? Have you experienced anything odd with RHEL?

**Comment by douglasulian** [comment] 2017-10-05 16:52
Just got the same behaviour installing **repo-epel** using on a Vagrant Centos/7 box version 1611.01.

**Comment by perryk** [comment] 2017-10-12 02:41
I have also encountered the same trouble after upgrading from Ansible 2.3 to 2.4 and using the Vagrant "centos/7" box.

**repo-epel** was actually ok when provisioning was attempted again, however, **repo-remi** was not.

I've just changed to using "geerlingguy/centos7" and am back in action.

Cheers.

**Comment by jamiejackson** [comment] 2017-10-14 22:40
I had been using `boxcutter/centos7`. Today, I had this problem, but now I'm trying `geerlingguy/centos7`. So far, so good.

**Comment by geerlingguy** [comment] 2017-10-18 04:26
Thanks everyone for posting these notes—good to know my Vagrant box is working well with the roles! I'm going to close the issue since it seems that there's at least one workaround... but feel free to post any more feedback/info here!

**Closed by geerlingguy** 2017-10-18 04:26 UTC

**Comment by leifmadsen** [comment] 2017-10-19 14:42
Yea strange, on a CentOS7 cloud image on an OpenStack deployment, I get the same thing the first run through, but not on the second run. It's like the data gets imported, but it fails for some odd reason. Maybe like a handle flush needs to happen... or... who knows at this point.

I can likely reproduce though by creating a new VM during the instantiation phase.

Ansible 2.4.0.0.

**Comment by pescobar** [comment] 2017-10-26 15:54
I have found a workaround by installing `epel-release` rpm before adding the keys.  More details here
https://github.com/ansible/ansible-container/issues/729#issuecomment-339705995
